# Generated by Django 2.2.1 on 2019-07-03 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_chating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 0, 25, 19, 453317)),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
