# Generated by Django 2.2.1 on 2019-07-04 11:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_chating', '0002_auto_20190704_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.UUID('c7f09ff0-ab67-4725-9de9-2fc55c9709ae'), max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Usrs',
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default=uuid.UUID('73983f8e-9cb4-449a-bd0f-fcf410d90f25'), max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 14, 22, 34, 195989)),
        ),
        migrations.AddField(
            model_name='usersauth',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_chating.Users'),
        ),
    ]
