# Generated by Django 2.2.1 on 2019-07-07 10:57

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_chating', '0006_auto_20190705_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='url',
            field=models.CharField(default=uuid.UUID('8d23694f-b66b-4b1f-8a8f-f44b147e78b0'), max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 7, 13, 57, 12, 958683)),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default=uuid.UUID('8701acee-49d5-4f27-97a9-db32f9eb1e13'), max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usersauth',
            name='token',
            field=models.CharField(default=uuid.UUID('57a282ea-f98a-4f78-8098-c038a76ac153'), max_length=100),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('senddate', models.DateTimeField(default=datetime.datetime(2019, 7, 7, 13, 57, 12, 962683))),
                ('identifier', models.CharField(default=uuid.UUID('4a1145db-5476-4d9b-995c-ec2e8eb89bef'), max_length=100)),
                ('chats', models.ManyToManyField(to='user_chating.Users')),
            ],
        ),
    ]
