# Generated by Django 2.2.1 on 2019-07-13 14:05

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_chating', '0008_auto_20190707_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersauth',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersauth',
            name='when_online',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 13, 14, 5, 58, 179465)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='url',
            field=models.CharField(default=uuid.UUID('db67f087-0c1c-4629-af91-2949ad561ceb'), max_length=100),
        ),
        migrations.AlterField(
            model_name='messages',
            name='identifier',
            field=models.CharField(default=uuid.UUID('106d67d9-9576-4ad5-88c4-13d1ee955b74'), max_length=100),
        ),
        migrations.AlterField(
            model_name='messages',
            name='senddate',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 13, 17, 5, 58, 182465)),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 13, 17, 5, 58, 179465)),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default=uuid.UUID('c74bd04c-f4ac-4643-836a-42ef5167f353'), max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usersauth',
            name='token',
            field=models.CharField(default=uuid.UUID('af42c3cc-cce9-4bef-bacc-470359c2c46c'), max_length=100),
        ),
    ]
