# Generated by Django 2.2.1 on 2019-07-13 17:03

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_chating', '0017_auto_20190713_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='url',
            field=models.CharField(default=uuid.UUID('05176de3-bc46-421e-882e-9dcec47b3511'), max_length=100),
        ),
        migrations.AlterField(
            model_name='messages',
            name='identifier',
            field=models.CharField(default=uuid.UUID('8e670783-e515-4f23-bb73-bb2573f6a3de'), max_length=100),
        ),
        migrations.AlterField(
            model_name='messages',
            name='senddate',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 13, 20, 3, 7, 901276)),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 13, 20, 3, 7, 882275)),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default=uuid.UUID('0ece20a1-f395-45f9-881c-a5e442d28951'), max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='when_online',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 13, 17, 3, 7, 882275)),
        ),
        migrations.AlterField(
            model_name='usersauth',
            name='token',
            field=models.CharField(default=uuid.UUID('3e52f269-4047-4766-afef-a9c09e9c2fbe'), max_length=100),
        ),
        migrations.AlterField(
            model_name='usersauth',
            name='when_online',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 13, 17, 3, 7, 883275)),
        ),
    ]
